version: '3'

services:
  videoparser:
    build:
      context: VideoParser
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    user: 1000:1000
    hostname: videoparser
    depends_on:
      - rabbitmq
    volumes:
      - ./config:/app/config
      - ./SharedData/:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    user: 1000:1000
    hostname: rabbitmq
    depends_on:
      - redis
    volumes:
      - ./config:/app/config
      - ./SharedData/:/data

  redis:
    image: redis:7.2.4-alpine
    ports:
      - 6379:6379
    hostname: redis
    volumes:
      - ./config:/app/config
      - ./SharedData/:/data

  flower:
    image: mher/flower:2.0
    command:
      [
        'celery',
        '--broker=amqp://rabbitmq:5672',
        'flower',
        '--port=5555'
      ]
    ports:
      - 5557:5555
    depends_on:
      - rabbitmq
    user: 1000:1000
    hostname: flower
    volumes:
      - ./config:/app/config
      - ./SharedData/:/data

  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    hostname: ollama
    volumes:
      - ./config:/app/config
      - ./SharedData/:/data
      - ./config/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  llm:
    build:
      context: LLM
      dockerfile: Dockerfile
    user: 1000:1000
    hostname: llm
    depends_on:
      - rabbitmq
      - ollama
    volumes:
      - ./config:/app/config
      - ./SharedData/:/data

  speechtexter:
    build:
      context: SpeechTexter
      dockerfile: Dockerfile
    hostname: speechtexter
    depends_on:
      - rabbitmq
    volumes:
      - ./config:/app/config
      - ./SharedData/:/data
      - ./config/speechtexter/:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  taskchecker:
    build:
      context: TaskChecker
      dockerfile: Dockerfile
    user: 1000:1000
    hostname: taskchecker
    depends_on:
      - rabbitmq
    volumes:
      - ./config:/app/config

  # redisinsight:
  #   image: redislabs/redisinsight:latest
  #   ports:
  #     - 8001:8001
  #   user: 1000:1000
  #   hostname: redisinsight
  #   depends_on:
  #     - redis
  #   volumes:
  #     - ./config:/app/config
  #     - ./SharedData/:/data

  webinterface:
    build:
      context: WebInterface
      dockerfile: Dockerfile
    hostname: webinterface
    user: 1000:1000
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - rabbitmq
      - taskchecker

    # develop:
    #   watch:
    #     - action: sync
    #       path: ./WebInterface/
    #       target: /app/
    volumes:
      - ./config:/app/config
      - ./SharedData/:/data

  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    hostname: postgres
    volumes:
      - ./config:/app/config
      - ./config/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: igbt
      POSTGRES_PASSWORD: bitircez
      POSTGRES_DB: igbt

  adminer:
    image: adminer:4.8.1
    ports:
      - 8080:8080
    hostname: adminer
    depends_on:
      - postgres

  tts:
    build:
      context: TTS
      dockerfile: Dockerfile
    hostname: tts
    depends_on:
      - rabbitmq
    volumes:
      - ./config:/app/config
      - ./SharedData/:/data
      - ./config/tts:/.local/share/tts
